In [6]:
import pandas as pd
data = {'Order ID': ['CA-2016-152156',
'CA-2016-152156',
'CA-2016-138688',
'US-2015-108966',
'US-2015-108966',
'CA-2014-115812',
'CA-2014-115812',
'CA-2014-115812',
'CA-2014-115812',
'CA-2014-115812',
'CA-2014-115812',
'CA-2014-115812',
'CA-2017-114412',
'CA-2016-161389',
'US-2015-118983',
'US-2015-118983',
'CA-2014-105893',
'CA-2014-167164',
'CA-2014-143336',
'CA-2014-143336',
'CA-2014-143336',
'CA-2016-137330',
'CA-2016-137330',
'US-2017-156909',
'CA-2015-106320',
'CA-2016-121755',
'CA-2016-121755',
'US-2015-150630',
'US-2015-150630',
'US-2015-150630',
'US-2015-150630',
'US-2015-150630',
'US-2015-150630',
'US-2015-150630',
'CA-2017-107727',
'CA-2016-117590',
'CA-2016-117590',
'CA-2015-117415',
'CA-2015-117415',
'CA-2015-117415',
'CA-2015-117415',
'CA-2017-120999',
'CA-2016-101343',
'CA-2017-139619',
'CA-2016-118255',
'CA-2016-118255',
'CA-2014-146703',
'CA-2016-169194',
'CA-2016-169194',
'CA-2015-115742',
'CA-2015-115742',
'CA-2015-115742',
'CA-2015-115742',
'CA-2016-105816',
'CA-2016-105816',
'CA-2016-111682',
'CA-2016-111682',
'CA-2016-111682',
'CA-2016-111682',
'CA-2016-111682',
'CA-2016-111682',
'CA-2016-111682',
'CA-2015-135545',
'CA-2015-135545',
'CA-2015-135545',
'CA-2015-135545',
'US-2015-164175',
'CA-2014-106376',
'CA-2014-106376',
'CA-2016-119823',
'CA-2016-106075',
'CA-2017-114440',
'US-2015-134026',
'US-2015-134026',
'US-2015-134026',
'US-2017-118038',
'US-2017-118038',
'US-2017-118038',
'US-2014-147606',
'CA-2016-127208',
'CA-2016-127208',
'CA-2014-139451',
'CA-2014-139451',
'CA-2015-149734',
'US-2017-119662',
'CA-2017-140088',
'CA-2017-155558',
'CA-2017-155558',
'CA-2016-159695',
'CA-2016-109806',
'CA-2016-109806',
'CA-2016-109806',
'CA-2015-149587',
'CA-2015-149587',
'CA-2015-149587',
'US-2017-109484',
'CA-2017-161018',
'CA-2017-157833',
'CA-2016-149223',
'CA-2016-158568',
], 'Order Date': ['42682',
'42682',
'42533',
'42288',
'42288',
'41799',
'41799',
'41799',
'41799',
'41799',
'41799',
'41799',
'42840',
'42709',
'42330',
'42330',
'41954',
'41772',
'41878',
'41878',
'41878',
'42713',
'42713',
'42932',
'42272',
'42385',
'42385',
'42264',
'42264',
'42264',
'42264',
'42264',
'42264',
'42264',
'43027',
'42712',
'42712',
'42365',
'42365',
'42365',
'42365',
'42988',
'42568',
'42997',
'42440',
'42440',
'41932',
'42541',
'42541',
'42112',
'42112',
'42112',
'42112',
'42715',
'42715',
'42538',
'42538',
'42538',
'42538',
'42538',
'42538',
'42538',
'42332',
'42332',
'42332',
'42332',
'42124',
'41978',
'41978',
'42525',
'42631',
'42992',
'42120',
'42120',
'42120',
'43078',
'43078',
'43078',
'41969',
'42533',
'42533',
'41924',
'41924',
'42250',
'43052',
'42883',
'43034',
'43034',
'42465',
'42630',
'42630',
'42630',
'42035',
'42035',
'42035',
'43045',
'43048',
'42903',
'42619',
'42611',
], 'Customer': ['EB-13930',
'EB-13930',
'MO-17950',
'JO-15550',
'JO-15550',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'RH-19600',
'GB-14530',
'PW-19030',
'RB-19570',
'RB-19570',
'JS-15940',
'SB-20170',
'HL-15040',
'HL-15040',
'HL-15040',
'DK-13225',
'DK-13225',
'CV-12805',
'NS-18640',
'AF-10885',
'AF-10885',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'JK-15625',
'BC-11125',
'JS-15595',
'JS-15595',
'CS-12355',
'CS-12355',
'CS-12355',
'CS-12355',
'JK-15205',
'SC-20695',
'JD-15895',
'CC-12475',
'CC-12475',
'PM-19135',
'CR-12580',
'CR-12580',
'TB-21400',
'TB-21400',
'TB-21400',
'TB-21400',
'SR-20740',
'SR-20740',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'BB-10990',
'EB-13870',
'EB-13870',
'EB-13870',
'EB-13870',
'QJ-19255',
'RC-19825',
'RC-19825',
'RE-19450',
'RB-19645',
'DL-13315',
'JL-15130',
'JL-15130',
'JL-15130',
'BO-11425',
'BO-11425',
'BO-11425',
'CL-12565',
'LM-17065',
'LM-17065',
'JM-15535',
'JM-15535',
'RP-19855',
'AG-10525',
'GH-14410',
'TS-21205',
'TS-21205',
'AF-10885',
'FM-14380',
'FM-14380',
'FM-14380',
'NS-18640',
'NS-18640',
'NS-18640',
'JR-15700',
'AJ-10945',
'BM-11575',
'CV-12805',
'DK-12835',
], 'Segment': ['Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Гишүүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Гишүүн',
'Гишүүн',
'Гишүүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Байгууллага',
'Гишүүн',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Байгууллага',
'Байгууллага',
'Байгууллага',
'Хувь хүн',
'Хувь хүн',
'Хувь хүн',
'Гишүүн',
'Гишүүн',
'Хувь хүн',
'Байгууллага',
'Гишүүн',
], 'Region':['Баянзүрх',
'Баянзүрх',
'Хан-Уул',
'Баянзүрх',
'Баянзүрх',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Баянзүрх',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
'Сүхбаатар',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Баянзүрх',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Сүхбаатар',
'Сүхбаатар',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Сүхбаатар',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Чингэлтэй',
'Хан-Уул',
'Хан-Уул',
'Баянзүрх',
'Сүхбаатар',
'Чингэлтэй',
'Баянзүрх',
'Баянзүрх',
'Баянзүрх',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Баянзүрх',
'Баянзүрх',
'Хан-Уул',
'Хан-Уул',
'Баянзүрх',
'Чингэлтэй',
'Баянзүрх',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Хан-Уул',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
'Чингэлтэй',
'Хан-Уул',
'Сүхбаатар',
'Хан-Уул',
'Чингэлтэй',
'Чингэлтэй',
],'Category':['Чихэр, печенье',
'OO ийн цаас, сальфетка',
'Чихэр, печенье',
'Хиам бууз',
'Ундаа ус',
'Жимс ногоо',
'Гурил будаа',
'Бичиг хэрэг',
'OO ийн цаас, сальфетка',
'Ундаа ус',
'OO ийн цаас, сальфетка',
'Ундаа ус',
'Архи пиво',
'Талх, нарийн боов',
'Ундаа ус',
'Ундаа ус',
'Саван бок',
'Зайрмаг',
'Бэлэн гоймон',
'Чихэр, печенье',
'Ундаа ус',
'OO ийн цаас, сальфетка',
'Хиам бууз',
'Зайрмаг',
'Гэр ахуй',
'Набор, шоколад, бохь',
'Чихэр, печенье',
'Гэр ахуй',
'Гурил будаа',
'Бэлэн гоймон',
'Ундаа ус',
'Жимс ногоо',
'Ундаа ус',
'Набор, шоколад, бохь',
'УНДАА УС',
'Самар чипс',
'Зайрмаг',
'ОО сойз',
'Гурил будаа',
'Архи пиво',
'Амтлагч',
'Гурил будаа',
'Чихэр, печенье',
'Ундаа ус',
'Ундаа ус',
'Саван бок',
'Бэлэн гоймон',
'Гурил будаа',
'Амтлагч',
'OO ийн цаас, сальфетка',
'Гурил будаа',
'Ундаа ус',
'Ундаа ус',
'Жимс ногоо',
'Амтлагч',
'OO ийн цаас, сальфетка',
'Самар чипс',
'Хиам бууз',
'OO ийн цаас, сальфетка',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Чихэр, печенье',
'Гоо сайхан',
'Саван бок',
'Чихэр, печенье',
'Гоо сайхан',
'Чихэр, печенье',
'Архи пиво',
'Архи пиво',
'Ундаа ус',
'Амтлагч',
'Гурил будаа',
'Самар чипс',
'Ундаа ус',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Гэр ахуй',
'Амтлагч',
'Жимс ногоо',
'Жимс ногоо',
'Чихэр, печенье',
'Самар чипс',
'Гэр ахуй',
'Ундаа ус',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Ундаа ус',
'Чихэр, печенье',
'Ундаа ус',
'Архи пиво',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Лаазалсан бүтээгдэхүүн, ургамлын тос',
'Чихэр, печенье',
'Гэр ахуй',
'Бэлэн гоймон',
'Чихэр, печенье',
'Архи пиво',
'Зайрмаг',
'Компот варенье, хүүхдийн тэжээл',
'Самар чипс',
'Набор, шоколад, бохь',
'Архи пиво',
'Бэлэн гоймон',
], 'Product name':['Shokolinsen 250 гр',
'Хэрэглээ 00ийн цаас',
'Алимтай жигнэмэг 230 гр',
'Золотой янта 500 гр',
'Punch 450 мл',
'Помидор том',
'Слава хивэг 400 гр',
'Үзгэн бал арилгадаг',
'Lady 20 ш',
'370 Жүүс 370 мл',
'Саль ариун 30 ш',
'Pysio 300 мл',
'A vodka 0.5',
'Өгөөж танзуур',
'Vita жимстэй ус 510 мл',
'Алое шилтэй 180 мл',
'Power 400 g',
'Пломбир на сливках 80 гр савтай',
'Удон гоймон ууттай',
'M&M 45 гр',
'Витафит ус 500 мл',
'Памперс №4',
'Solpro майонез 3 л 67 %',
'Магнат 80 гр',
'Хувцасны өлгүүр 5 ш алаг',
'Шингэн чихэр',
'Akuku резин 90 гр',
'Сахлын татуурга Gilette',
'Русский сахар 250 гр',
'Бэлэн гоймон төмстэй',
'Хүслийн ундаа 500 мл',
'Помидор том',
'Arizona лаазтай 680 мл',
'Jacobs кофе',
'Өглөө сүү',
'Амт чипс 55 гр',
'Эгоист 65 гр',
'Colgate total 100 гр',
'Слава гурвалжин будаа 650 гр',
'Хараа 0.75 цэвэр',
'Вигора 200 гр',
'Давс 1 кг',
'Mini cracker 350 гр',
'Arizona лаазтай 680 мл',
'Тоник лаазтай 330 мл',
'Tide 450 гр авто',
'Paldo king noodle 110 гр',
'Цесна 25 кг',
'Appetita плова',
'Саль ариун 100 ш',
'Слава каш 1 кг',
'Моя семъя 1 л',
'Зуун наст 1.25 мл',
'Мандарин',
'Appetita будаатай хуурга',
'Цэвэрхэн 00ийн цаас',
'Siesta үзэм 200 гр',
'Махеевь салатны 400 мл',
'Selpak 2 хайрцаг',
'Oleina тос 1 л',
'Чихэр кг Кокос 400 гр',
'Nivea тос 50 мл',
'Омо 100 гр',
'Өгөөж вафли',
'Head & Shoulders 400 мл',
'Жимстэй чокопай 6 ш',
'Соёолж 2.5 л',
'Тэргүүн 0.5',
'Витсамо ус 500 мл',
'Дашида 50 гр',
'Заантай будаа 5 кг',
'Lays чипс 80 гр',
'Алое шилтэй 180 мл',
'Хавиргатай рагу 454 гр',
'Хутга 1 ш',
'Appetita будаатай хуурга',
'Нандин чавга 250 гр',
'Чинжүү',
'Чихэр кг Конфет Кино 400 гр',
'Cocoro 100 гр',
'3н өнгийн алчуур',
'Оргилуун ус жимстэй 500 мл',
'Видан зөгийн бал',
'Сор жүүс 200 мл',
'Гурвалжин шоко 22 гр',
'Гоё тетра 1 л',
'Хараа 0.75 цэвэр',
'Шпрот урт татдаг 190 гр',
'Bagro хүрэн манжингийн салат 500 мл',
'Цагаан самар 50 гр',
'Махны мод дугуй',
'Биг ланч 110 гр савтай',
'Custard 6 ш',
'Алтантүрүү 0.5',
'Фифти фифти 180 гр',
'Hainich нухаш',
'Lays чипс 80 гр',
'Монстров 23 гр',
'Арвай 0.100',
'Тэйсти гоймон 110 гр',
],'Price':['3300',
'500',
'3100',
'2800',
'1150',
'4000',
'750',
'2500',
'2200',
'850',
'2200',
'1700',
'9000',
'3000',
'1050',
'1100',
'1600',
'1200',
'1200',
'1000',
'450',
'1000',
'7700',
'2500',
'2500',
'2100',
'1500',
'550',
'1100',
'1200',
'1050',
'4000',
'2500',
'240',
'2600',
'1300',
'900',
'4400',
'2100',
'11500',
'1500',
'200',
'3500',
'2500',
'1250',
'4100',
'2200',
'45000',
'450',
'1400',
'2000',
'3200',
'1900',
'4500',
'350',
'400',
'2700',
'1700',
'4800',
'4200',
'5500',
'3300',
'900',
'1950',
'12000',
'2300',
'5700',
'7600',
'500',
'800',
'13200',
'2300',
'1100',
'3400',
'3000',
'350',
'2000',
'4000',
'3000',
'2300',
'1100',
'1050',
'3300',
'500',
'600',
'1600',
'11500',
'3500',
'2200',
'500',
'13000',
'2300',
'2300',
'12500',
'2750',
'3300',
'2300',
'500',
'2000',
'1800',
],'Quantity':[2,
3,
2,
5,
2,
7,
4,
6,
3,
5,
9,
4,
3,
3,
5,
3,
6,
2,
2,
3,
4,
7,
7,
2,
3,
2,
3,
7,
2,
3,
2,
6,
6,
2,
3,
7,
5,
9,
3,
3,
4,
4,
2,
2,
2,
2,
4,
3,
2,
6,
6,
2,
1,
7,
5,
6,
5,
5,
2,
2,
4,
1,
2,
6,
3,
4,
5,
8,
4,
2,
1,
3,
8,
2,
1,
3,
3,
3,
5,
1,
3,
5,
1,
7,
3,
2,
1,
2,
7,
3,
2,
1,
2,
3,
2,
1,
7,
3,
6,
7,
],'Sales':[6600,
1500,
6200,
14000,
2300,
28000,
3000,
15000,
6600,
4250,
19800,
6800,
27000,
9000,
5092.5,
3201,
9600,
2400,
2400,
3000,
1800,
7000,
53900,
5000,
7500,
4200,
4500,
3850,
2200,
3600,
2100,
24000,
15000,
480,
7566,
9100,
4500,
38412,
6111,
33465,
5820,
800,
7000,
5000,
2500,
8200,
8800,
135000,
900,
8400,
12000,
6400,
1900,
31500,
1750,
2400,
13500,
8500,
9600,
8400,
22000,
3300,
1800,
11700,
36000,
9200,
27645,
60800,
2000,
1600,
13200,
6900,
8800,
6800,
3000,
1050,
6000,
12000,
15000,
2300,
3300,
5250,
3300,
3500,
1746,
3200,
11500,
7000,
14938,
1500,
26000,
2300,
4600,
37500,
5500,
3201,
15617,
1500,
12000,
12222,
]}
data
shop = pd.DataFrame(data)
shop

,Order ID,Order Date,Customer,Segment,Region,Category,Product name,Price,Quantity,Sales
0,CA-2016-152156,42682,EB-13930,Хувь хүн,Баянзүрх,"Чихэр, печенье",Shokolinsen 250 гр,3300,2,6600.0
1,CA-2016-152156,42682,EB-13930,Хувь хүн,Баянзүрх,"OO ийн цаас, сальфетка",Хэрэглээ 00ийн цаас,500,3,1500.0
2,CA-2016-138688,42533,MO-17950,Байгууллага,Хан-Уул,"Чихэр, печенье",Алимтай жигнэмэг 230 гр,3100,2,6200.0
3,US-2015-108966,42288,JO-15550,Хувь хүн,Баянзүрх,Хиам бууз,Золотой янта 500 гр,2800,5,14000.0
4,US-2015-108966,42288,JO-15550,Хувь хүн,Баянзүрх,Ундаа ус,Punch 450 мл,1150,2,2300.0
...,...,...,...,...,...,...,...,...,...,...
95,US-2017-109484,43045,JR-15700,Гишүүн,Хан-Уул,"Компот варенье, хүүхдийн тэжээл",Hainich нухаш,3300,1,3201.0
96,CA-2017-161018,43048,AJ-10945,Гишүүн,Сүхбаатар,Самар чипс,Lays чипс 80 гр,2300,7,15617.0
97,CA-2017-157833,42903,BM-11575,Хувь хүн,Хан-Уул,"Набор, шоколад, бохь",Монстров 23 гр,500,3,1500.0
98,CA-2016-149223,42619,CV-12805,Байгууллага,Чингэлтэй,Архи пиво,Арвай 0.100,2000,6,12000.0
99,CA-2016-158568,42611,DK-12835,Гишүүн,Чингэлтэй,Бэлэн гоймон,Тэйсти гоймон 110 гр,1800,7,12222.0

In [7]:
#1 Эхний 10 мөрийг сонгож авна уу.
shop[0:10]

,Order ID,Order Date,Customer,Segment,Region,Category,Product name,Price,Quantity,Sales
0,CA-2016-152156,42682,EB-13930,Хувь хүн,Баянзүрх,"Чихэр, печенье",Shokolinsen 250 гр,3300,2,6600.0
1,CA-2016-152156,42682,EB-13930,Хувь хүн,Баянзүрх,"OO ийн цаас, сальфетка",Хэрэглээ 00ийн цаас,500,3,1500.0
2,CA-2016-138688,42533,MO-17950,Байгууллага,Хан-Уул,"Чихэр, печенье",Алимтай жигнэмэг 230 гр,3100,2,6200.0
3,US-2015-108966,42288,JO-15550,Хувь хүн,Баянзүрх,Хиам бууз,Золотой янта 500 гр,2800,5,14000.0
4,US-2015-108966,42288,JO-15550,Хувь хүн,Баянзүрх,Ундаа ус,Punch 450 мл,1150,2,2300.0
5,CA-2014-115812,41799,RH-19600,Хувь хүн,Хан-Уул,Жимс ногоо,Помидор том,4000,7,28000.0
6,CA-2014-115812,41799,RH-19600,Хувь хүн,Хан-Уул,Гурил будаа,Слава хивэг 400 гр,750,4,3000.0
7,CA-2014-115812,41799,RH-19600,Хувь хүн,Хан-Уул,Бичиг хэрэг,Үзгэн бал арилгадаг,2500,6,15000.0
8,CA-2014-115812,41799,RH-19600,Хувь хүн,Хан-Уул,"OO ийн цаас, сальфетка",Lady 20 ш,2200,3,6600.0
9,CA-2014-115812,41799,RH-19600,Хувь хүн,Хан-Уул,Ундаа ус,370 Жүүс 370 мл,850,5,4250.0

In [8]:
#2 78-88 дугаар мөрөнд байгаа мэдээллээс Product Name, Sales багануудыг харуулна уу.
data1=shop[["Product name","Sales"]]
data2=data1[79:88]
data2

                  Product name    Sales
79               Cocoro 100 гр   2300.0
80            3н өнгийн алчуур   3300.0
81  Оргилуун ус жимстэй 500 мл   5250.0
82            Видан зөгийн бал   3300.0
83             Сор жүүс 200 мл   3500.0
84        Гурвалжин шоко 22 гр   1746.0
85               Гоё тетра 1 л   3200.0
86            Хараа 0.75 цэвэр  11500.0
87     Шпрот урт татдаг 190 гр   7000.0

In [9]:
#3 Quantity болон Sales баганыг сонгож авна 
data3=shop[["Quantity","Sales"]]
data3

    Quantity    Sales
0          2   6600.0
1          3   1500.0
2          2   6200.0
3          5  14000.0
4          2   2300.0
..       ...      ...
95         1   3201.0
96         7  15617.0
97         3   1500.0
98         6  12000.0
99         7  12222.0

[100 rows x 2 columns]

In [10]:
#4 Quantity болон Sales баганын нийлбэрүүдийг харуулна уу.
data4=shop[["Quantity","Sales"]].sum()
data4

Quantity        374.0
Sales       1115166.5
dtype: float64

In [11]:
#5 Product Name баганыг сонгож авна уу.
data5=shop[["Product name"]]
data5

               Product name
0        Shokolinsen 250 гр
1       Хэрэглээ 00ийн цаас
2   Алимтай жигнэмэг 230 гр
3       Золотой янта 500 гр
4              Punch 450 мл
..                      ...
95            Hainich нухаш
96          Lays чипс 80 гр
97           Монстров 23 гр
98              Арвай 0.100
99     Тэйсти гоймон 110 гр

[100 rows x 1 columns]

In [13]:
#6 Product Name баганын давхардаагүй утгуудыг харуулна уу
data6=shop[~shop.duplicated('Product name')]
data6["Product name"]

0          Shokolinsen 250 гр
1         Хэрэглээ 00ийн цаас
2     Алимтай жигнэмэг 230 гр
3         Золотой янта 500 гр
4                Punch 450 мл
               ...
94         Фифти фифти 180 гр
95              Hainich нухаш
97             Монстров 23 гр
98                Арвай 0.100
99       Тэйсти гоймон 110 гр
Name: Product name, Length: 94, dtype: object

In [14]:
#7 Product Name баганын давхардаагүй утгууд нийт хэд байгааг тоолж харуулна уу
print(len(data6.index))

94

In [17]:
#8 Product Name баганын давхардсан утгуудыг харуулна уу.
data9=shop[df.duplicated('Product name')]["Product name"]
data9

31                 Помидор том
43      Arizona лаазтай 680 мл
72          Алое шилтэй 180 мл
75    Appetita будаатай хуурга
86            Хараа 0.75 цэвэр
96             Lays чипс 80 гр
Name: Product name, dtype: object

In [22]:
#9 Order ID баганын давхардаагүй утгууд нийт хэд байгааг тоолж харуулна уу.
data10=df[df.duplicated('Order ID')]["Order ID"]
print(len(data10.index))

50

In [26]:
#10 Бараа тус бүрээс хэдэн ширхэгийг зарсаныг харуулна уу
data6=shop[~df.duplicated('Product name')]
data6["Product name"]

0          Shokolinsen 250 гр
1         Хэрэглээ 00ийн цаас
2     Алимтай жигнэмэг 230 гр
3         Золотой янта 500 гр
4                Punch 450 мл
               ...
94         Фифти фифти 180 гр
95              Hainich нухаш
97             Монстров 23 гр
98                Арвай 0.100
99       Тэйсти гоймон 110 гр
Name: Product name, Length: 94, dtype: object

In [24]:
ab=shop.groupby(["Product name"]).sum()
ab

                          Quantity    Sales
Product name
370 Жүүс 370 мл                  5   4250.0
3н өнгийн алчуур                 3   3300.0
A vodka 0.5                      3  27000.0
Akuku резин 90 гр                3   4500.0
Appetita будаатай хуурга         8   2800.0
...                            ...      ...
Эгоист 65 гр                     5   4500.0
Үзгэн бал арилгадаг              6  15000.0
Өглөө сүү                        3   7566.0
Өгөөж вафли                      6  11700.0
Өгөөж танзуур                    3   9000.0

[94 rows x 2 columns]

In [25]:
ad=shop.groupby(["Order ID"]).sum()
ad

                Quantity     Sales
Order ID
CA-2014-105893         6    9600.0
CA-2014-106376        12   62800.0
CA-2014-115812        38   83450.0
CA-2014-139451         6    8550.0
CA-2014-143336         9    7200.0
CA-2014-146703         4    8800.0
CA-2014-167164         2    2400.0
CA-2015-106320         3    7500.0
CA-2015-115742        15   28700.0
CA-2015-117415        19   83808.0
CA-2015-135545        15   58700.0
CA-2015-149587         7   47600.0
CA-2015-149734         7    3500.0
CA-2016-101343         2    7000.0
CA-2016-105816        12   33250.0
CA-2016-106075         1   13200.0
CA-2016-109806         6   29800.0
CA-2016-111682        25   67700.0
CA-2016-117590        12   13600.0
CA-2016-118255         4   10700.0
CA-2016-119823         2    1600.0
CA-2016-121755         5    8700.0
CA-2016-127208         4    5600.0
CA-2016-137330        14   60900.0
CA-2016-138688         2    6200.0
CA-2016-149223         6   12000.0
CA-2016-152156         5    8100.0
CA-2016-158568         7   12222.0
CA-2016-159695         7   14938.0
CA-2016-161389         3    9000.0
CA-2016-169194         5  135900.0
CA-2017-107727         3    7566.0
CA-2017-114412         3   27000.0
CA-2017-114440         3    6900.0
CA-2017-120999         4     800.0
CA-2017-139619         2    5000.0
CA-2017-140088         2    3200.0
CA-2017-155558         3   18500.0
CA-2017-157833         3    1500.0
CA-2017-161018         7   15617.0
US-2014-147606         5   15000.0
US-2015-108966         7   16300.0
US-2015-118983         8    8293.5
US-2015-134026        11   18600.0
US-2015-150630        28   51230.0
US-2015-164175         5   27645.0
US-2017-109484         1    3201.0
US-2017-118038         9   19050.0
US-2017-119662         3    1746.0
US-2017-156909         2    5000.0

In [105]:
#11 Хамгийн өндөр дүнтэй борлуулалтыг (Order ID) олно уу.
#12 Хамгийн өндөр дүнтэй зарагдсан барааг (Sales) олно уу. 
df.sort_values(["Sales"],ascending=False)

,Order ID,Order Date,Customer,Segment,Region,Category,Product name,Price,Quantity,Sales
47,CA-2016-169194,42541,CR-12580,Хувь хүн,Сүхбаатар,Гурил будаа,Цесна 25 кг,45000,3,135000.0
67,CA-2014-106376,41978,RC-19825,Байгууллага,Хан-Уул,Архи пиво,Тэргүүн 0.5,7600,8,60800.0
22,CA-2016-137330,42713,DK-13225,Байгууллага,Чингэлтэй,Хиам бууз,Solpro майонез 3 л 67 %,7700,7,53900.0
37,CA-2015-117415,42365,CS-12355,Гишүүн,Чингэлтэй,ОО сойз,Colgate total 100 гр,4400,9,38412.0
93,CA-2015-149587,42035,NS-18640,Хувь хүн,Чингэлтэй,Архи пиво,Алтантүрүү 0.5,12500,3,37500.0
...,...,...,...,...,...,...,...,...,...,...
89,CA-2016-109806,42630,FM-14380,Байгууллага,Хан-Уул,"Чихэр, печенье",Цагаан самар 50 гр,500,3,1500.0
75,US-2017-118038,43078,BO-11425,Байгууллага,Чингэлтэй,Амтлагч,Appetita будаатай хуурга,350,3,1050.0
48,CA-2016-169194,42541,CR-12580,Хувь хүн,Сүхбаатар,Амтлагч,Appetita плова,450,2,900.0
41,CA-2017-120999,42988,JK-15205,Байгууллага,Чингэлтэй,Гурил будаа,Давс 1 кг,200,4,800.0
33,US-2015-150630,42264,JK-15625,Хувь хүн,Сүхбаатар,"Набор, шоколад, бохь",Jacobs кофе,240,2,480.0